### PR TITLE
avb: Update 'setcap' command for gst-launch

### PR DESCRIPTION
**Pull request by edersondisouza**
Now that avtpsink uses ETF, applications also need CAP_NET_ADMIN, so we
must add that to documentation.

### CODE REVIEW

**Comment by vcgomes** [comment]
Looks good.

**Comment by andrew-elder** [comment]
Does this change apply to a particular version of avtpsink?

**Comment by edersondisouza** [comment]
> Does this change apply to a particular version of avtpsink?

Considering that the first GStreamer version with avtpsink will be the upcoming 1.18 - with this new requirement already on, I'd say there's no versions to worry about.

**Comment by vedangpatel1** [comment]
LGTM!

**Comment by andrew-elder** [comment]
Can someone with merge privileges please merge this?

**Comment by aguedes** [comment]
Merging this PR now. Thanks @edersondisouza!

**Pull request merged**
